export const environment = {
  production: true,
  sneakers: [
    {
      id: 100,
      image: '../assets/images/Nike/Nike1.webp',
      brand: 'Nike',
      name: 'Men Air Force 1 React Leather Sneakers',
      description:
        'A pair of round toe white sneakers ,has regular styling. Lace-ups detail. Leather upper. Cushioned footbed. Nike React details are incorporated into the outsole. Hook-and-loop strap on the heel updates the look and lets you personalise your fit. Rubber outsole adds traction and durability. Textured and patterned outsole',
      gender: 'Male',
      price: 11995,
    },
    {
      id: 101,
      image: '../assets/images/Nike/Nike2.webp',
      brand: 'Nike',
      name: 'Men Grey & Black Air Presto Sneakers',
      description:
        'A pair of round toe grey sneakers ,has regular styling, Lace-ups detail Textile upper Cushioned footbed The stretchy mesh upper creates a cosy, sock-like fit while adding breathability. The iconic midfoot TPU cage adds contrast to the stretchy synthetic upper while helping support your foot. The flex grooves in the sole help with the natural motion of the foot Textured and patterned outsole.',
      gender: 'Male',
      price: 13995,
    },
    {
      id: 102,
      image: '../assets/images/Nike/Nike3.webp',
      brand: 'Nike',
      name: 'Men White AIR MAX 270 Sneakers',
      description:
        'A pair of round toe white sneakers ,has regular styling, Lace-ups detail Synthetic and textile upper. The Max Air 270 unit delivers unrivalled, all-day comfort. Woven and synthetic fabric on the upper provides a lightweight fit and airy feel. The foam midsole feels soft and comfortable. The stretchy inner sleeve and booty-like construction creates a personalised fit. Rubber on the outsole adds traction and durability. Mesh details for an airy feel Pull tab Cushioned footbed Textured and patterned outsole',
      gender: 'Male',
      price: 13995,
    },
    {
      id: 103,
      image: '../assets/images/Nike/Nike4.webp',
      brand: 'Nike',
      name: 'Men Black & Purple Colourblocked AIR MAX 90 GTX Leather Sneakers',
      description:
        'A pair of round toe black sneakers ,has regular styling, Lace-ups detail Leather upper Cushioned footbed Textured and patterned outsole Waterproof GORE-TEX upper helps keep you dry so you can focus on the adventure. Leather vamp adds durability and helps resist the elements. Originally designed for performance running, visible Nike Air cushioning puts the history of comfort beneath your feet. Waffle-inspired outsole delivers traction, durability and heritage style. Padded, low-cut collar looks sleek and feels great.',
      gender: 'Male',
      price: 13995,
    },
    {
      id: 104,
      image: '../assets/images/Nike/Nike5.webp',
      brand: 'Nike',
      name: 'Men Yellow Solid Sneakers',
      description:
        'A pair of round toe yellow, has regular styling, Lace-ups detail Textile upper Cushioned footbed Textured and patterned outsole Nike Air cushioning reduces the weight of the shoe without reducing performance',
      gender: 'Male',
      price: 10345,
    },
    {
      id: 105,
      image: '../assets/images/Nike/Nike6.webp',
      brand: 'Nike',
      name: 'Women Pink CRATER IMPACT Sneakers',
      description:
        "A pair of round toe pink sneakers ,has regular styling, Lifted Crater foam midsole is made from 12% recycled content, adds stability and has a unique speckled appearance. The upper's thoughtful and modern design includes straight-edged overlays for construction efficiency and scrap waste reduction. Made from at least 25% recycled material by weight 1-piece webbing eyestay mixes DIY flavour with an urban touch while adding to the pattern-efficient build The athletics-inspired silhouette features sleek angles and a padded, low-cut collar for easy styling that's comfortable Mesh on the upper keeps it airy and lightweight Stitched-on Swoosh design adds a wild, zebra-like aesthetic and keeps with the efficient design Rubber details on the outsole feature 15% Nike Grind and add traction and durability Embroidered Swoosh design Pinwheel logo indicates that this shoe is made from at least 20% recycled materials",
      gender: 'Female',
      price: 5391,
    },
    {
      id: 106,
      image: '../assets/images/Nike/Nike7.webp',
      brand: 'Nike',
      name: 'Women White Leather Air Max 90 Sneakers',
      description:
        'A pair of round toe white sneakers, has regular styling, Lace-ups detail Leather upper Cushioned footbed Textured and patterned outsole',
      gender: 'Female',
      price: 8921,
    },
    {
      id: 107,
      image: '../assets/images/Nike/Nike8.webp',
      brand: 'Nike',
      name: 'Women Air Force 1 07 Leather Sneakers',
      description:
        'A pair of round toe white & Maroon sneakers, has regular styling Lace-ups detail Leather upper Cushioned footbed Stitched synthetic overlays on the upper add heritage style and durability. Originally designed for performance hoops, Nike Air cushioning adds lightweight comfort. Crater Foam midsole provides stability and a unique speckled appearance. Rubber outsole with classic hoops pivot circles and star design adds durable traction. Textured and patterned outsole',
      gender: 'Female',
      price: 9695,
    },
    {
      id: 108,
      image: '../assets/images/Nike/Nike9.webp',
      brand: 'Nike',
      name: 'Women Air Force 1 Leather Sneakers',
      description:
        "A pair of round toe white sneakers ,has mid-top styling, Lace-ups detail Leather upper Leather in the upper ages to soft perfection and features a durable construction reminiscent of '80s b-ball. Cork-infused outsole and liquor-inspired colours add an artisan touch. Adjustable strap around the collar lets you customise styling and fit. From tough stitching to pristine materials to the cupsole design, it delivers durable style that's smoother than backboard glass. Cushioned footbed Textured and patterned outsole",
      gender: 'Female',
      price: 11295,
    },
    {
      id: 109,
      image: '../assets/images/Nike/Nike10.webp',
      brand: 'Nike',
      name: 'Women Black & Off-White Air Max Flyknit Sneakers',
      description:
        'A pair of round toe black sneakers ,has regular styling, Lace-ups detail Textile upper Soft synthetic suede detailing adds a classic touch. Collar sculpts the ankle for an athletics-inspired look. Foam midsole delivers springy cushioning. Cushioned footbed Textured and patterned outsole',
      gender: 'Female',
      price: 14245,
    },
    {
      id: 200,
      image: '../assets/images/Adidas/Adidas1.webp',
      brand: 'Adidas',
      name: 'Men Black & Pink Woven Design Checked NMD_R1 Sneakers',
      description:
        "The adidas NMD has only been around since 2015, but it's already a modern icon. Rooted in running designs from the archives but packed with modern technology, it's always been about innovation. This pair of the shoes keeps that spirit going strong. See the bold 3D pattern that wraps around the foot? That's just the latest evolution of the fearless NMD attitude. Step in and catch an energy-filled ride to the future -- or through your day.",
      gender: 'Male',
      price: 11699,
    },
    {
      id: 201,
      image: '../assets/images/Adidas/Adidas2.webp',
      brand: 'Adidas',
      name: 'Men Black Solid Woven Design Nmd_R1 Sneakers',
      description:
        "Running-inspired style made for everyday exploration. This remastered version of the adidas NMD_R1 is the cutting-edge evolution of the original '80s-inspired shoes with painted plug edges and colorful lace tips to add fresh updates. A stretchy knit upper crafted hugs your foot for comfort on the go. Long commutes and slick city sidewalks are no problem, thanks to the BOOST cushioning and grippy rubber outsole beneath your feet",
      gender: 'Male',
      price: 12999,
    },
    {
      id: 202,
      image: '../assets/images/Adidas/Adidas3.webp',
      brand: 'Adidas',
      name: 'Men White & Red Colourblocked ZX 2K Boost 2.0 Sneakers',
      description:
        'Bring the future into your present day with the adidas ZX 2K BOOST 2.0 shoes. Taking inspiration from the adidas ZX line that you love, these shoes bring fresh energy. The mesh-based upper pairs bright and smooth accents to create a bold, unapologetic look. BOOST cushioning delivers energy return and instant comfort with each step to keep you going. Made in part with recycled content generated from production waste, e.g. cutting scraps, and post-consumer household waste to avoid the larger environmental impact of producing virgin content.',
      gender: 'Male',
      price: 11199,
    },
    {
      id: 203,
      image: '../assets/images/Adidas/Adidas4.webp',
      brand: 'Adidas',
      name: 'Men Grey Woven Design Leather Nmd_R1 V3 Sneakers',
      description:
        "A play on transparency, these adidas NMD_R1 V3 Shoes continue to build on the NMD franchise's signature expression of tactical tech. Here's what you need to know about the BOOST cushioning: it makes every step feel supported. Which is great, since you take a lot of them throughout the day. The other thing to know is that it's partially encapsulated in TPU, met by the TPU heel plugs that signal that these are in fact NMD trainers. They have a laser-cut upper, complete with embroidered details for a fresh take on the iconic style.",
      gender: 'Male',
      price: 14399,
    },
    {
      id: 204,
      image: '../assets/images/Adidas/Adidas5.webp',
      brand: 'Adidas',
      name: 'Men Green Solid ZX 8000 Parley Sneakers',
      description:
        "Since ZX first debuted as a line of running shoes in the '80s, it has been a laboratory for innovation. With these adidas shoes, the legacy continues. We partnered with Parley for the Oceans and revamped the cult-classic style with future generations of sneakerheads in mind. Just scan the QR code to find out more about the origins of the recycled materials in these iconic shoes. This shoe's upper is made with a high-performance yarn which contains at least 50% Parley Ocean Plastic -- reimagined plastic waste, intercepted on remote islands, beaches, coastal communities and shorelines, preventing it from polluting our ocean. The other 50% of the yarn is recycled polyester.",
      gender: 'Male',
      price: 13999,
    },
    {
      id: 205,
      image: '../assets/images/Adidas/Adidas6.webp',
      brand: 'Adidas',
      name: 'Women ULTRABOOST DNA SHOES',
      description: '',
      gender: 'Female',
      price: 17999,
    },
    {
      id: 206,
      image: '../assets/images/Adidas/Adidas7.webp',
      brand: 'Adidas',
      name: 'Women FORUM BONEGA SHOES',
      description: '',
      gender: 'Female',
      price: 7199.5,
    },
    {
      id: 207,
      image: '../assets/images/Adidas/Adidas8.webp',
      brand: 'Adidas',
      name: 'Women NMD_R1 SHOES',
      description: '',
      gender: 'Female',
      price: 7799.5,
    },
    {
      id: 208,
      image: '../assets/images/Adidas/Adidas9.webp',
      brand: 'Adidas',
      name: 'Women NMD_R1 THEBE MAGUGU SHOES',
      description: '',
      gender: 'Female',
      price: 7799.5,
    },
    {
      id: 209,
      image: '../assets/images/Adidas/Adidas10.webp',
      brand: 'Adidas',
      name: 'Women ADIDAS SUPERSTAR X LEGO® SHOES',
      description: '',
      gender: 'Female',
      price: 13999,
    },
    {
      id: 300,
      image: '../assets/images/Puma/Puma1.webp',
      brand: 'Puma',
      name: 'Men Grey PINT Sneakers',
      description:
        'A pair of round toe grey sneakers ,has regular styling, Lace-ups detail Textile upper Cushioned footbed low boot construction with lace closure Textured and patterned outsole.',
      gender: 'Male',
      price: 3439,
    },
    {
      id: 301,
      image: '../assets/images/Puma/Puma2.webp',
      brand: 'Puma',
      name: 'Men Black Lite Pro Sneakers',
      description:
        'Synthetic Upper provides durability , Low boot Construction & Lace closure, PUMA Logo for subtle look, Rubber Outsole for better traction',
      gender: 'Male',
      price: 2279,
    },
    {
      id: 302,
      image: '../assets/images/Puma/Puma3.webp',
      brand: 'Puma',
      name: 'Men Black Sneakers',
      description:
        'A pair of round toe black sneakers ,has regular styling, Lace-ups detail Mesh upper Cushioned footbed Textured and patterned outsole',
      gender: 'Male',
      price: 2159,
    },
    {
      id: 303,
      image: '../assets/images/Puma/Puma4.webp',
      brand: 'Puma',
      name: 'Men Grey Cblock IDP Sneakers',
      description:
        'A pair of round-toe grey striped sneakers, has regular styling, lace-up detail Mesh upper with synthetic overlays Cushioned footbed Textured and patterned outsole',
      gender: 'Male',
      price: 3374,
    },
    {
      id: 304,
      image: '../assets/images/Puma/Puma5.webp',
      brand: 'Puma',
      name: 'Men Navy Blue Green Level Sneakers',
      description:
        'A pair of round-toe navy blue & green sneakers, has regular styling, lace-up detail Mesh upper Cushioned footbed Textured and patterned outsole',
      gender: 'Male',
      price: 2235,
    },
    {
      id: 305,
      image: '../assets/images/Puma/Puma6.webp',
      brand: 'Puma',
      name: 'Women Black Better Foam Prowl Deco Glam Slip-On Training Shoes',
      description:
        'A pair of black shoes, has regular styling, slip-on detail Low boot Recycled features in upper Medium cushioning Neutral shoe pronation 8.0 heel-to-toe drop PUMA Wordmark on the lateral side PUMA Cat logo on the toe',
      gender: 'Female',
      price: 3119,
    },
    {
      id: 306,
      image: '../assets/images/Puma/Puma7.webp',
      brand: 'Puma',
      name: 'Women Softride Sophia Slip Shine Women White Walking Shoes',
      description:
        "Here's cause for celebration: a brand-new Softride shoe with a distinctly feminine edge. Combining plush and comfy Softride foam with a SoftFoam+ sockliner, these shoes are as comfortable as you can imagine. The upper has a true slip-on construction while the outsole is designed with light training in mind thanks to zoned rubber pods. Add big and bold PUMA branding to all that, and you have a pair of shoes that will make your next Walk as stylish as it is comfy. SoftFoam+: PUMA's comfort sockliner for instant step-in and long-lasting comfort that provides soft cushioning every step of your day.  Low boot Upper has true slip-on construction highlighted by gore and moulding",
      gender: 'Female',
      price: 3794,
    },
    {
      id: 307,
      image: '../assets/images/Puma/Puma8.webp',
      brand: 'Puma',
      name: 'Women Navy Blue Textured Regular Reflex Sneakers',
      description:
        'A pair of round toe navy blue sneakers, has regular styling Lace-ups detail Knitted textile (Synthetic) & mesh upper provides breathability & durabilty Cushioned footbed Textured and patterned rubber outsole for traction Low boot construction PUMA Logo for subtle branding',
      gender: 'Female',
      price: 2999,
    },
    {
      id: 308,
      image: '../assets/images/Puma/Puma9.webp',
      brand: 'Puma',
      name: 'Women Black Zora In Motion Sneakers',
      description:
        'A pair of round toe black sneakers ,has regular styling, Lace-ups detail Mesh upper Cushioned footbed Textured and patterned outsole',
      gender: 'Female',
      price: 5399,
    },
    {
      id: 309,
      image: '../assets/images/Puma/Puma10.webp',
      brand: 'Puma',
      name: 'Women Beige & Turquoise Blue Pacific Maze Colourblocked Sneakers',
      description:
        'A pair of round toe beige & turquoise blue sneakers, has regular styling, Textile upper for breathable comfort Full lace closure Full length EVA midsole Mesh Upper provides excellent Rubber outsole provides traction and control Contrast PUMA Formstrip overlay at lateral side Webbing heel and tongue pull loops',
      gender: 'Female',
      price: 3599,
    },
    {
      id: 400,
      image: '../assets/images/Fila/Fila1.webp',
      brand: 'Fila',
      name: 'Men Grey Textured Sneakers',
      description:
        'A pair of round toe grey sneakers ,has regular styling, Lace-ups detail Pu upper Cushioned footbed Textured and patterned outsole',
      gender: 'Male',
      price: 3219,
    },
    {
      id: 401,
      image: '../assets/images/Fila/Fila2.webp',
      brand: 'Fila',
      name: 'Men Colourblocked Sneakers',
      description:
        'A pair of round toe black sneakers ,has mid-top styling, Lace-ups detail Pu upper Cushioned footbed Textured and patterned outsole',
      gender: 'Male',
      price: 1359,
    },
    {
      id: 402,
      image: '../assets/images/Fila/Fila3.webp',
      brand: 'Fila',
      name: 'Men White Colourblocked PU Sneakers',
      description:
        'A pair of round toe white ,has regular styling, Lace-ups detail upper Cushioned footbed Textured and patterned outsole',
      gender: 'Male',
      price: 2279,
    },
    {
      id: 403,
      image: '../assets/images/Fila/Fila4.webp',
      brand: 'Fila',
      name: 'Men Grey Perforations Sneakers',
      description:
        'A pair of round toe grey sneakers ,has mid-top styling, Lace-ups detail Pu upper Cushioned footbed Textured and patterned outsole',
      gender: 'Male',
      price: 1879,
    },
    {
      id: 404,
      image: '../assets/images/Fila/Fila5.webp',
      brand: 'Fila',
      name: 'Men White PU Sneakers',
      description:
        'A pair of round toe white sneakers ,has mid-top styling, Lace-ups detail Pu upper Cushioned footbed Textured and patterned outsole',
      gender: 'Male',
      price: 2159,
    },
    {
      id: 405,
      image: '../assets/images/Fila/Fila6.webp',
      brand: 'Fila',
      name: 'Women White PU EXCURSION Sneakers',
      description:
        'A pair of round toe white ,has regular styling, Lace-ups detail upper Cushioned footbed Textured and patterned outsole',
      gender: 'Female',
      price: 4999,
    },
    {
      id: 406,
      image: '../assets/images/Fila/Fila7.webp',
      brand: 'Fila',
      name: 'Women Black Textured Sneakers',
      description:
        'A pair of round toe black sneakers ,has regular styling, Lace-ups detail Pu upper Cushioned footbed Textured and patterned outsole',
      gender: 'Female',
      price: 2799,
    },
    {
      id: 407,
      image: '../assets/images/Fila/Fila8.webp',
      brand: 'Fila',
      name: 'Women White Printed Canvas Sneakers',
      description:
        'A pair of round toe white sneakers ,has mid-top styling, Lace-ups detail Canvasupper Cushioned footbed Textured and patterned outsole',
      gender: 'Female',
      price: 5599,
    },
    {
      id: 408,
      image: '../assets/images/Fila/Fila9.webp',
      brand: 'Fila',
      name: 'Women White & Gold High-Top Basketball Non-Marking Leopard Print Shoes',
      description:
        'A pair of white, gold & black shoes has high-top Styling lace-ups detail Upper Cushioned footbed Textured and patterned outsole',
      gender: 'Female',
      price: 10999,
    },
    {
      id: 409,
      image: '../assets/images/Fila/Fila10.webp',
      brand: 'Fila',
      name: 'Women Grey Lace Ups Sneakers',
      description:
        'A pair of round toe grey sneakers ,has regular styling, Lace-ups detail Pu upper Cushioned footbed Textured and patterned outsole',
      gender: 'Female',
      price: 4299,
    },
    {
      id: 500,
      image: '../assets/images/Skechers/Skechers1.webp',
      brand: 'Skechers',
      name: 'Men Black ELITE FLEX Sneakers',
      description:
        'A pair of round-toe black sneakers, has regular styling, lace-up detail Soft woven engineered mesh nearly one piece fabric upper Lace up sporty walking sneaker design Stitching accents Engineered knit mesh with woven in open weave front and side panels Solid color design Interwoven ventilating panels Side S logo Heel fabric overlay panel with SKECHERS logo detail and top pull on loop Lace up front Padded collar and tongue Soft fabric shoe lining Air Cooled Memory Foam cushioned comfort insole Elite Flex midsole with superior impact cushioning protection and remarkable energy return Highly flexible articulated midsole and outsole design for freedom of movement Textured channel design midsole finish Flexible outsole with flexible articulated traction design Cushioned footbed',
      gender: 'Male',
      price: 5399,
    },
    {
      id: 501,
      image: '../assets/images/Skechers/Skechers2.webp',
      brand: 'Skechers',
      name: 'Men Black Dlites Arch Fit Sneakers',
      description:
        'A pair of round toe black sneakers ,has regular styling, Lace-ups detail Mesh upper Smooth leather, synthetic and mesh upper with lace-up front Solid color upper with contrast side overlay and detailing Cushioned footbed Textured and patterned outsole',
      gender: 'Male',
      price: 7649,
    },
    {
      id: 502,
      image: '../assets/images/Skechers/Skechers3.webp',
      brand: 'Skechers',
      name: 'Men White & Black Glide Step Head Start Sneakers',
      description:
        'A pair of round toe white & black sneakers, has regular styling Lace-ups detail Mesh upper Cushioned footbed Textured and patterned outsole Athletic engineered mesh knit upper with lace-up front Super flexible rubber traction outsole',
      gender: 'Male',
      price: 6374,
    },
    {
      id: 503,
      image: '../assets/images/Skechers/Skechers4.webp',
      brand: 'Skechers',
      name: 'Men White Track Syntac Sneakers',
      description:
        'A pair of round toe white sneakers ,has regular styling, Lace-ups detail Mesh upper Cushioned footbed Flexible cushioning midsole and traction outsole ideal for fitness training Textured and patterned outsole',
      gender: 'Male',
      price: 4949,
    },
    {
      id: 504,
      image: '../assets/images/Skechers/Skechers5.webp',
      brand: 'Skechers',
      name: 'Men Navy Blue Escape Plan Encompass Sneakers',
      description:
        'A pair of round toe navy blue sneakers ,has regular styling, Lace-ups detail Mesh upper Cushioned footbed Textured and patterned outsole',
      gender: 'Male',
      price: 8499,
    },
    {
      id: 505,
      image: '../assets/images/Skechers/Skechers6.webp',
      brand: 'Skechers',
      name: 'Women Navy Blue Flex Appeal 4.0 - Active Flow Sneakers',
      description:
        'A pair of round toe navy blue sneakers ,has regular styling, Lace-ups detail Mesh upper Cushioned footbed Lightweight shock-absorbing midsole Super flexible traction outsole Textured and patterned outsole',
      gender: 'Female',
      price: 4899,
    },
    {
      id: 506,
      image: '../assets/images/Skechers/Skechers7.webp',
      brand: 'Skechers',
      name: 'Women Black Air Dynamight Big Step Slip-On Sneakers',
      description:
        'A pair of round toe black slip-on sneakers, has regular styling Slip-on detail Mesh upper Soft woven heathered mesh and synthetic upper Slip-on sporty comfort training sneaker design Cushioned footbed Textured and patterned outsole',
      gender: 'Female',
      price: 3899,
    },
    {
      id: 507,
      image: '../assets/images/Skechers/Skechers8.webp',
      brand: 'Skechers',
      name: 'Women Navy Blue Arch Fit Vibrant Step Sneakers',
      description:
        'A pair of round toe navy blue sneakers, has regular styling, Lace-ups detail Mesh upper Cushioned footbed Textured and patterned outsole Ombre athletic mono mesh upper with lace-up front Cushioned lightweight midsole with flexible traction outsole',
      gender: 'Female',
      price: 7199,
    },
    {
      id: 508,
      image: '../assets/images/Skechers/Skechers9.webp',
      brand: 'Skechers',
      name: 'Women Black & Blue Flex Appeal 3.0 Iconic Sneakers',
      description:
        'A pair of round toe black sneakers ,has regular styling, Lace-ups detail Mesh upper Cushioned footbed Knit-in dramatic ombre design with side scatter transition designs Knit in open weave front panel for breathable comfort Sporty woven texture mesh design with breathable panels Textured and patterned outsole',
      gender: 'Female',
      price: 5949,
    },
    {
      id: 509,
      image: '../assets/images/Skechers/Skechers10.webp',
      brand: 'Skechers',
      name: 'Women Air Dynamight Sneakers',
      description:
        'A pair of round toe black sneakers ,has regular styling, Lace-ups detail Mesh upper Cushioned footbed Heel fabric overlay panel with SKECHERS logo and pull on top tab Padded collar and tongue Textured and patterned outsole',
      gender: 'Female',
      price: 6174,
    },
    {
      id: 600,
      image: '../assets/images/TommyHilfiger/TommyHilfiger1.webp',
      brand: 'Tommy Hilfiger',
      name: 'Men White Leather Sneakers',
      description:
        'A pair of round toe white sneakers, has regular styling, Lace-ups detail Leather upper Cushioned footbed Textured and patterned outsole',
      gender: 'Male',
      price: 5599,
    },
    {
      id: 601,
      image: '../assets/images/TommyHilfiger/TommyHilfiger2.webp',
      brand: 'Tommy Hilfiger',
      name: 'Men Navy Blue Leather Sneakers',
      description:
        'A pair of round toe navy blue sneakers, has regular styling Lace-ups detail Leather upper Cushioned footbed Textured and patterned outsole',
      gender: 'Male',
      price: 6799,
    },
    {
      id: 602,
      image: '../assets/images/TommyHilfiger/TommyHilfiger3.webp',
      brand: 'Tommy Hilfiger',
      name: 'Men Beige Solid Sneakers',
      description:
        'A pair of beige solid round toesneakers, has regular styling, Lace-ups detail Synthetic upper Cushioned footbed Textured and patterned outsole',
      gender: 'Male',
      price: 6749,
    },
    {
      id: 603,
      image: '../assets/images/TommyHilfiger/TommyHilfiger4.webp',
      brand: 'Tommy Hilfiger',
      name: 'Men Blue & Beige Colourblocked Regular Sneakers',
      description:
        'A pair of round toe blue, beige, and navy blue sneakers, has regular styling Lace-ups detail Textile and leather upper Cushioned footbed Textured and patterned EVA outsole',
      gender: 'Male',
      price: 7409,
    },
    {
      id: 604,
      image: '../assets/images/TommyHilfiger/TommyHilfiger5.webp',
      brand: 'Tommy Hilfiger',
      name: 'Men Sage Green Colourblocked Sneakers',
      description:
        'A pair of round toe green sneakers ,has regular styling, Lace-ups detail Synthetic upper Cushioned footbed Textured and patterned outsole',
      gender: 'Male',
      price: 6629,
    },
    {
      id: 605,
      image: '../assets/images/TommyHilfiger/TommyHilfiger6.webp',
      brand: 'Tommy Hilfiger',
      name: 'Women Black COURT CUPSOLE Perforations Leather Sneakers',
      description:
        'A pair of round toe black sneakers, has regular styling, Lace-ups detail Leather upper Cushioned footbed Textured and patterned outsole',
      gender: 'Female',
      price: 7599,
    },
    {
      id: 606,
      image: '../assets/images/TommyHilfiger/TommyHilfiger7.webp',
      brand: 'Tommy Hilfiger',
      name: 'Women White Solid Sneakers',
      description:
        'A pair of round toe white Sneakers, has regular styling Lace-ups detail Textile upper Cushioned footbed Textured and patterned outsole',
      gender: 'Female',
      price: 5279,
    },
    {
      id: 607,
      image: '../assets/images/TommyHilfiger/TommyHilfiger8.webp',
      brand: 'Tommy Hilfiger',
      name: 'Women Red & Navy Blue Colourblocked Leather Sneakers',
      description:
        'A pair of round toe red sneakers ,has regular styling, Lace-ups detail Leather upper Cushioned footbed Textured and patterned outsole',
      gender: 'Female',
      price: 8639,
    },
    {
      id: 608,
      image: '../assets/images/TommyHilfiger/TommyHilfiger9.webp',
      brand: 'Tommy Hilfiger',
      name: 'Women White Textured Regular Sneakers With Tech Foam Midsole',
      description:
        'A pair of round toe white sneakers with Tech Foam Midsole, has regular styling Lace-ups detail Mesh and synthetic (other materials) upper Cushioned footbed Textured and patterned EVA outsole',
      gender: 'Female',
      price: 7999,
    },
    {
      id: 609,
      image: '../assets/images/TommyHilfiger/TommyHilfiger10.webp',
      brand: 'Tommy Hilfiger',
      name: 'Women Grey Elite 7 Winter Sneakers',
      description:
        'A pair of round toe grey sneakers, has regular styling Lace-up detail Synthetic upper Cushioned footbed Textured and patterned outsole',
      gender: 'Female',
      price: 9499,
    },
  ],
};
